apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wavq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0019-tenant/tkrw-pr712-0075-0019-app/devfile-sample-wavq@sha256:2b93bb966c4a0479c6e746ab209b1138192931ab8016249b0df83cd1e8555ad0
        name: my-nodejs
        resources: {}
status: {}
